### ISSUE TITLE
Support .Net Standard 2.0

### ISSUE THREAD

**Issue by pulla2908** [duffleit/fluentOptionals#9]
We have a NuGet package which depends on this library. At the moment we target `.Net Framework`. We are going to change this to `.NET Standard 2.0` instead in order to support `.NET Core`, `.Net 5` and still `.NET Framework`. Because of that it would be helpful if this library would also support `.Net Standard 2.0`.

Any plans to support `.Net Standard 2.0`?

**Comment by pulla2908** [comment]
I will create a change for that soon. You will get a pull request then.

**Comment by duffleit** [comment]
Perfect, thanks a lot — looking forward :)
But shouldn't https://github.com/duffleit/fluentOptionals/pull/8 already fix the issue?

**Comment by pulla2908** [comment]
@duffleit #8 does not really help me in my case. In my scenario I want to build a package which targets `.NET Standard 2.0` only. It depends on this library. It should be consumed by `.NET Framework` and `.NET Core` and `.NET5`. Because of that it would be easier for me to integrate your library if it also targets `.NET Standard 2.0`. That is my reason :-)

**Comment by pulla2908** [comment]
I can give you another example why it makes sense to support `.NET Standard 2.0`. Let's pretend there is (an older) project which still targets full framework (e.g. `net472`). For this project you can already start adding and using external libraries which targets a compatible `.NET Standard` (which can be up to version 2.0 but not 2.1). 

Later when you move your project to `.NET Core` or `.NET5` you can still use these external libraries without updating them. You just continue using them. This is a big benefit to prepare for future changes!

Do you see my point?
